// <auto-generated />
namespace ShopApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddtblUsersRolesrenametblUserRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddtblUsersRolesrenametblUserRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "202007260728114_Add tblUsersRoles rename tblUserRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
